arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.5
  # kinematics_solver_attempts: 3 # Kinematics solver doesn't support #attempts anymore, but only a timeout.